CREATE TABLE employee (
    id INT PRIMARY KEY,
    first_name character varying(50),
    last_name character varying(50)
);

CREATE TABLE loader (
    id INT NOT NULL,
    machine_name character varying(50)
);

CREATE TABLE tipper (
    id INT PRIMARY KEY,
    machine_name character varying(50),
    payload INT
);

CREATE TABLE shift_employee (
    id INT PRIMARY KEY,
    employee_id INT REFERENCES employee(id),
    pos_x real,
    pos_y real,
    moment timestamp,
    current_status character varying(50)
);

CREATE TABLE shift_loader (
    id INT PRIMARY KEY,
    employee_id INT REFERENCES employee(id),
    loader_id INT REFERENCES loader(id),
    is_loading boolean,
    ore_count INT,
    pos_x real,
    pos_y real,
    moment timestamp,
    current_status character varying(50)
);

CREATE TABLE shift_tipper (
    id INT PRIMARY KEY,
    employee_id INT REFERENCES employee(id),
    tipper_id INT REFERENCES tipper(id),
    ore_type character varying,
    ore_count INT,
    pos_x real,
    pos_y real,
    moment timestamp,
    current_status character varying(50)
);

insert into tipper (id, machine_name, payload) values (1, 'CAT', 50);
insert into tipper (id, machine_name, payload) values (2, 'Belaz', 90);
insert into tipper (id, machine_name, payload) values (3, 'CAT', 40);
insert into tipper (id, machine_name, payload) values (4, 'Belaz', 70);
insert into tipper (id, machine_name, payload) values (5, 'CAT', 50);
insert into tipper (id, machine_name, payload) values (6, 'Belaz', 50);
insert into tipper (id, machine_name, payload) values (7, 'CAT', 90);
insert into tipper (id, machine_name, payload) values (8, 'Belaz', 40);
insert into tipper (id, machine_name, payload) values (9, 'CAT', 70);
insert into tipper (id, machine_name, payload) values (10, 'Belaz', 50);
insert into tipper (id, machine_name, payload) values (11, 'CAT', 50);
insert into tipper (id, machine_name, payload) values (12, 'Belaz', 90);
insert into tipper (id, machine_name, payload) values (13, 'CAT', 40);
insert into tipper (id, machine_name, payload) values (14, 'Belaz', 70);
insert into tipper (id, machine_name, payload) values (15, 'CAT', 50);

insert into loader (id, machine_name) values (1, 'CAT');
insert into loader (id, machine_name) values (2, 'Belaz');
insert into loader (id, machine_name) values (3, 'CAT');
insert into loader (id, machine_name) values (4, 'CAT');
insert into loader (id, machine_name) values (5, 'Belaz');
insert into loader (id, machine_name) values (6, 'CAT');
insert into loader (id, machine_name) values (7, 'CAT');
insert into loader (id, machine_name) values (8, 'Belaz');
insert into loader (id, machine_name) values (9, 'CAT');
insert into loader (id, machine_name) values (10, 'Belaz');
insert into loader (id, machine_name) values (11, 'CAT');
insert into loader (id, machine_name) values (12, 'Belaz');
insert into loader (id, machine_name) values (13, 'CAT');
insert into loader (id, machine_name) values (14, 'Belaz');
insert into loader (id, machine_name) values (15, 'CAT');

insert into employee (id, first_name, last_name) values (1, 'Spence', 'Prys');
insert into employee (id, first_name, last_name) values (2, 'Becka', 'Widdows');
insert into employee (id, first_name, last_name) values (3, 'Stanislas', 'Wain');
insert into employee (id, first_name, last_name) values (4, 'Carmelia', 'Hilary');
insert into employee (id, first_name, last_name) values (5, 'Evelin', 'Mac');
insert into employee (id, first_name, last_name) values (6, 'Gray', 'Affron');
insert into employee (id, first_name, last_name) values (7, 'Gregorio', 'Willock');
insert into employee (id, first_name, last_name) values (8, 'Padget', 'Caslake');
insert into employee (id, first_name, last_name) values (9, 'Salim', 'McCathy');
insert into employee (id, first_name, last_name) values (10, 'Rob', 'Madsen');
insert into employee (id, first_name, last_name) values (11, 'Jeannine', 'Richardsson');
insert into employee (id, first_name, last_name) values (12, 'Roosevelt', 'Tunnah');
insert into employee (id, first_name, last_name) values (13, 'Manda', 'Goosey');
insert into employee (id, first_name, last_name) values (14, 'Austine', 'Shiels');
insert into employee (id, first_name, last_name) values (15, 'Robyn', 'Josovitz');
insert into employee (id, first_name, last_name) values (16, 'Waylin', 'Kirsopp');
insert into employee (id, first_name, last_name) values (17, 'Ethel', 'Fortie');
insert into employee (id, first_name, last_name) values (18, 'Jarib', 'Rowland');
insert into employee (id, first_name, last_name) values (19, 'Ignatius', 'Kuzma');
insert into employee (id, first_name, last_name) values (20, 'Georgie', 'Lomasna');
insert into employee (id, first_name, last_name) values (21, 'Lorry', 'Vigneron');
insert into employee (id, first_name, last_name) values (22, 'Rene', 'McVrone');
insert into employee (id, first_name, last_name) values (23, 'Trefor', 'Kulas');
insert into employee (id, first_name, last_name) values (24, 'Moina', 'Chillcot');
insert into employee (id, first_name, last_name) values (25, 'D''arcy', 'Salthouse');
insert into employee (id, first_name, last_name) values (26, 'Ester', 'Cayet');
insert into employee (id, first_name, last_name) values (27, 'Georgiana', 'Lintall');
insert into employee (id, first_name, last_name) values (28, 'King', 'Rawling');
insert into employee (id, first_name, last_name) values (29, 'Layne', 'Garbert');
insert into employee (id, first_name, last_name) values (30, 'Susi', 'Rein');
insert into employee (id, first_name, last_name) values (31, 'Mignonne', 'Dormer');
insert into employee (id, first_name, last_name) values (32, 'Elvyn', 'Gossage');
insert into employee (id, first_name, last_name) values (33, 'Berni', 'Whittingham');
insert into employee (id, first_name, last_name) values (34, 'Hulda', 'Sadgrove');
insert into employee (id, first_name, last_name) values (35, 'Bradly', 'Crix');
insert into employee (id, first_name, last_name) values (36, 'Cy', 'Tidcombe');
insert into employee (id, first_name, last_name) values (37, 'Cecily', 'Orsman');
insert into employee (id, first_name, last_name) values (38, 'Aylmer', 'Wibrew');
insert into employee (id, first_name, last_name) values (39, 'Kimble', 'Ros');
insert into employee (id, first_name, last_name) values (40, 'Freddy', 'Gosker');
insert into employee (id, first_name, last_name) values (41, 'Pierson', 'Littler');
insert into employee (id, first_name, last_name) values (42, 'Jacky', 'McGee');
insert into employee (id, first_name, last_name) values (43, 'Stormie', 'Thurnham');
insert into employee (id, first_name, last_name) values (44, 'Charmain', 'Beeson');
insert into employee (id, first_name, last_name) values (45, 'Corette', 'Bramstom');
insert into employee (id, first_name, last_name) values (46, 'Dona', 'Limpricht');
insert into employee (id, first_name, last_name) values (47, 'Lothaire', 'Iannetti');
insert into employee (id, first_name, last_name) values (48, 'Merwin', 'Petofi');
insert into employee (id, first_name, last_name) values (49, 'Lavinie', 'Saffill');
insert into employee (id, first_name, last_name) values (50, 'Alphonse', 'McConnell');
insert into employee (id, first_name, last_name) values (51, 'Meredeth', 'Rubenczyk');
insert into employee (id, first_name, last_name) values (52, 'Dayna', 'Briztman');
insert into employee (id, first_name, last_name) values (53, 'Caressa', 'Gillbey');
insert into employee (id, first_name, last_name) values (54, 'Helli', 'Boswell');
insert into employee (id, first_name, last_name) values (55, 'Laurens', 'Weetch');
insert into employee (id, first_name, last_name) values (56, 'Tanhya', 'Shobbrook');
insert into employee (id, first_name, last_name) values (57, 'Lois', 'O''Clery');
insert into employee (id, first_name, last_name) values (58, 'Alexia', 'Kinney');
insert into employee (id, first_name, last_name) values (59, 'Gabi', 'McGrorty');
insert into employee (id, first_name, last_name) values (60, 'Merci', 'Ellsworthe');
insert into employee (id, first_name, last_name) values (61, 'Katerine', 'Uccelli');
insert into employee (id, first_name, last_name) values (62, 'Emalee', 'Kordas');
insert into employee (id, first_name, last_name) values (63, 'Zonda', 'Franchyonok');
insert into employee (id, first_name, last_name) values (64, 'Winslow', 'Tong');
insert into employee (id, first_name, last_name) values (65, 'Isadora', 'Pomfrey');
insert into employee (id, first_name, last_name) values (66, 'Albertina', 'Bignall');
insert into employee (id, first_name, last_name) values (67, 'Cynde', 'Davers');
insert into employee (id, first_name, last_name) values (68, 'Jacques', 'Broscombe');
insert into employee (id, first_name, last_name) values (69, 'Francklin', 'Pyvis');
insert into employee (id, first_name, last_name) values (70, 'Johanna', 'Gerwood');
insert into employee (id, first_name, last_name) values (71, 'Alida', 'Attle');
insert into employee (id, first_name, last_name) values (72, 'Randene', 'Trump');
insert into employee (id, first_name, last_name) values (73, 'Dru', 'Minmagh');
insert into employee (id, first_name, last_name) values (74, 'Zechariah', 'Farfalameev');
insert into employee (id, first_name, last_name) values (75, 'Concordia', 'Jeppe');
insert into employee (id, first_name, last_name) values (76, 'Leroi', 'Hartright');
insert into employee (id, first_name, last_name) values (77, 'Marci', 'Clucas');
insert into employee (id, first_name, last_name) values (78, 'Norean', 'Thompson');
insert into employee (id, first_name, last_name) values (79, 'Drake', 'Bindley');
insert into employee (id, first_name, last_name) values (80, 'Eldin', 'McLeish');
insert into employee (id, first_name, last_name) values (81, 'Hannie', 'Pinchin');
insert into employee (id, first_name, last_name) values (82, 'Anselma', 'Francesconi');
insert into employee (id, first_name, last_name) values (83, 'Kerry', 'Tutchener');
insert into employee (id, first_name, last_name) values (84, 'Lem', 'Fidgett');
insert into employee (id, first_name, last_name) values (85, 'Aurelea', 'Meriet');
insert into employee (id, first_name, last_name) values (86, 'Melita', 'Drakeley');
insert into employee (id, first_name, last_name) values (87, 'Eli', 'Osgerby');
insert into employee (id, first_name, last_name) values (88, 'Leonora', 'Bewsy');
insert into employee (id, first_name, last_name) values (89, 'Eal', 'Meriot');
insert into employee (id, first_name, last_name) values (90, 'Bunnie', 'Mossdale');
insert into employee (id, first_name, last_name) values (91, 'Cal', 'Humphrys');
insert into employee (id, first_name, last_name) values (92, 'Jan', 'Abramowitz');
insert into employee (id, first_name, last_name) values (93, 'Brit', 'Keson');
insert into employee (id, first_name, last_name) values (94, 'Arnuad', 'Cathel');
insert into employee (id, first_name, last_name) values (95, 'Farica', 'Rozec');
insert into employee (id, first_name, last_name) values (96, 'Irita', 'Polhill');
insert into employee (id, first_name, last_name) values (97, 'Sanson', 'Tollerfield');
insert into employee (id, first_name, last_name) values (98, 'Ulises', 'Darque');
insert into employee (id, first_name, last_name) values (99, 'Aldridge', 'O''Hagerty');
insert into employee (id, first_name, last_name) values (100, 'Dalis', 'Fennelly');
insert into employee (id, first_name, last_name) values (101, 'Greta', 'Exeter');
insert into employee (id, first_name, last_name) values (102, 'Rem', 'Rawlyns');
insert into employee (id, first_name, last_name) values (103, 'Edmon', 'Deards');
insert into employee (id, first_name, last_name) values (104, 'Iolande', 'Catt');
insert into employee (id, first_name, last_name) values (105, 'Katerine', 'Scannell');
insert into employee (id, first_name, last_name) values (106, 'Gorden', 'Buzek');
insert into employee (id, first_name, last_name) values (107, 'Rube', 'Taylorson');
insert into employee (id, first_name, last_name) values (108, 'Ignazio', 'Rizzetti');
insert into employee (id, first_name, last_name) values (109, 'Nedi', 'McParlin');
insert into employee (id, first_name, last_name) values (110, 'Aarika', 'Gilvary');
insert into employee (id, first_name, last_name) values (111, 'Anny', 'Ousley');
insert into employee (id, first_name, last_name) values (112, 'Nadia', 'Rodman');
insert into employee (id, first_name, last_name) values (113, 'Floyd', 'Backler');
insert into employee (id, first_name, last_name) values (114, 'Sheree', 'Elener');
insert into employee (id, first_name, last_name) values (115, 'Queenie', 'Splaven');
insert into employee (id, first_name, last_name) values (116, 'Thoma', 'O''Fogarty');
insert into employee (id, first_name, last_name) values (117, 'Riki', 'Murty');
insert into employee (id, first_name, last_name) values (118, 'Stafani', 'Munroe');
insert into employee (id, first_name, last_name) values (119, 'Ardenia', 'Corneljes');
insert into employee (id, first_name, last_name) values (120, 'Doyle', 'Semper');
insert into employee (id, first_name, last_name) values (121, 'Barry', 'Jagielski');
insert into employee (id, first_name, last_name) values (122, 'Reta', 'Geggie');
insert into employee (id, first_name, last_name) values (123, 'Carleen', 'Hansbury');
insert into employee (id, first_name, last_name) values (124, 'Fulvia', 'Chambers');
insert into employee (id, first_name, last_name) values (125, 'Merry', 'Deuss');
insert into employee (id, first_name, last_name) values (126, 'Drugi', 'Juara');
insert into employee (id, first_name, last_name) values (127, 'Elmo', 'Trusler');
insert into employee (id, first_name, last_name) values (128, 'Jemmy', 'Seamark');
insert into employee (id, first_name, last_name) values (129, 'Marlo', 'Grayland');
insert into employee (id, first_name, last_name) values (130, 'Johannes', 'Praundlin');
insert into employee (id, first_name, last_name) values (131, 'Cullie', 'Dunnett');
insert into employee (id, first_name, last_name) values (132, 'Walliw', 'Orford');
insert into employee (id, first_name, last_name) values (133, 'Eamon', 'Kenneway');
insert into employee (id, first_name, last_name) values (134, 'Gardie', 'Lax');
insert into employee (id, first_name, last_name) values (135, 'Tildie', 'Dyet');
insert into employee (id, first_name, last_name) values (136, 'Chrysa', 'Nobbs');
insert into employee (id, first_name, last_name) values (137, 'Claretta', 'Gatheral');
insert into employee (id, first_name, last_name) values (138, 'Raphaela', 'Franchyonok');
insert into employee (id, first_name, last_name) values (139, 'Yehudit', 'Delia');
insert into employee (id, first_name, last_name) values (140, 'Norene', 'Ygo');
insert into employee (id, first_name, last_name) values (141, 'Cassey', 'Brundle');
insert into employee (id, first_name, last_name) values (142, 'Myrtice', 'Penzer');
insert into employee (id, first_name, last_name) values (143, 'Erhard', 'Readman');
insert into employee (id, first_name, last_name) values (144, 'Aggi', 'Luberti');
insert into employee (id, first_name, last_name) values (145, 'Kristel', 'Phillpot');
insert into employee (id, first_name, last_name) values (146, 'Maximo', 'Olenichev');
insert into employee (id, first_name, last_name) values (147, 'Montgomery', 'St. Leger');
insert into employee (id, first_name, last_name) values (148, 'Renelle', 'Sherrin');
insert into employee (id, first_name, last_name) values (149, 'Thorndike', 'Normadell');
insert into employee (id, first_name, last_name) values (150, 'Tye', 'Baldazzi');
insert into employee (id, first_name, last_name) values (151, 'Mabel', 'Walcot');
insert into employee (id, first_name, last_name) values (152, 'Ruttger', 'Lankester');
insert into employee (id, first_name, last_name) values (153, 'Courtney', 'Ezzell');
insert into employee (id, first_name, last_name) values (154, 'Paquito', 'Leving');
insert into employee (id, first_name, last_name) values (155, 'Blakeley', 'Pratley');
insert into employee (id, first_name, last_name) values (156, 'Clywd', 'Northill');
insert into employee (id, first_name, last_name) values (157, 'Timothee', 'Lamswood');
insert into employee (id, first_name, last_name) values (158, 'Sidonnie', 'Petrasch');
insert into employee (id, first_name, last_name) values (159, 'Jaye', 'Hales');
insert into employee (id, first_name, last_name) values (160, 'Bell', 'Dalliston');
insert into employee (id, first_name, last_name) values (161, 'Lambert', 'Brydone');
insert into employee (id, first_name, last_name) values (162, 'Brande', 'Oldroyd');
insert into employee (id, first_name, last_name) values (163, 'Deny', 'Longlands');
insert into employee (id, first_name, last_name) values (164, 'Conrado', 'Twinberrow');
insert into employee (id, first_name, last_name) values (165, 'Allyce', 'Blazhevich');
insert into employee (id, first_name, last_name) values (166, 'Salomi', 'Langrick');
insert into employee (id, first_name, last_name) values (167, 'Gwenny', 'Momery');
insert into employee (id, first_name, last_name) values (168, 'Hasheem', 'Karczinski');
insert into employee (id, first_name, last_name) values (169, 'Dell', 'Fyfield');
insert into employee (id, first_name, last_name) values (170, 'Lowell', 'Flori');
insert into employee (id, first_name, last_name) values (171, 'Edgar', 'Kevis');
insert into employee (id, first_name, last_name) values (172, 'Reeba', 'Keigher');
insert into employee (id, first_name, last_name) values (173, 'Pancho', 'Coghlin');
insert into employee (id, first_name, last_name) values (174, 'Nicolette', 'Nevill');
insert into employee (id, first_name, last_name) values (175, 'Ode', 'Caplin');
insert into employee (id, first_name, last_name) values (176, 'Ashlin', 'Newlin');
insert into employee (id, first_name, last_name) values (177, 'Heath', 'Mackro');
insert into employee (id, first_name, last_name) values (178, 'Bat', 'Simeonov');
insert into employee (id, first_name, last_name) values (179, 'Harley', 'Leat');
insert into employee (id, first_name, last_name) values (180, 'Erny', 'Naismith');
insert into employee (id, first_name, last_name) values (181, 'Wyatan', 'Harniman');
insert into employee (id, first_name, last_name) values (182, 'Lenna', 'Roback');
insert into employee (id, first_name, last_name) values (183, 'Olivier', 'Birdwhistle');
insert into employee (id, first_name, last_name) values (184, 'Guenevere', 'Grace');
insert into employee (id, first_name, last_name) values (185, 'Manda', 'Shorrock');
insert into employee (id, first_name, last_name) values (186, 'Almeda', 'Nabarro');
insert into employee (id, first_name, last_name) values (187, 'Carson', 'De Vries');
insert into employee (id, first_name, last_name) values (188, 'Farica', 'Kenright');
insert into employee (id, first_name, last_name) values (189, 'Goldarina', 'De Santos');
insert into employee (id, first_name, last_name) values (190, 'Aylmar', 'Dibson');
insert into employee (id, first_name, last_name) values (191, 'Kacey', 'Shallo');
insert into employee (id, first_name, last_name) values (192, 'Dion', 'Borg-Bartolo');
insert into employee (id, first_name, last_name) values (193, 'Dasha', 'Gwynn');
insert into employee (id, first_name, last_name) values (194, 'Aleece', 'Coal');
insert into employee (id, first_name, last_name) values (195, 'Jarrod', 'Polak');
insert into employee (id, first_name, last_name) values (196, 'Zelda', 'Wark');
insert into employee (id, first_name, last_name) values (197, 'Jeremias', 'Beadle');
insert into employee (id, first_name, last_name) values (198, 'Leonard', 'Gookey');
insert into employee (id, first_name, last_name) values (199, 'Madalena', 'Constanza');
insert into employee (id, first_name, last_name) values (200, 'Patty', 'Barbery');
insert into employee (id, first_name, last_name) values (201, 'Berta', 'Giottoi');
insert into employee (id, first_name, last_name) values (202, 'Mickie', 'Wordley');
insert into employee (id, first_name, last_name) values (203, 'Camilla', 'Quinney');
insert into employee (id, first_name, last_name) values (204, 'Harlin', 'Minkin');
insert into employee (id, first_name, last_name) values (205, 'Cassius', 'Garlinge');
insert into employee (id, first_name, last_name) values (206, 'Demetris', 'McCurry');
insert into employee (id, first_name, last_name) values (207, 'Charla', 'Hartington');
insert into employee (id, first_name, last_name) values (208, 'Cristiano', 'Folling');
insert into employee (id, first_name, last_name) values (209, 'Susi', 'Millom');
insert into employee (id, first_name, last_name) values (210, 'Tobin', 'Daud');
insert into employee (id, first_name, last_name) values (211, 'Barbette', 'McQuode');
insert into employee (id, first_name, last_name) values (212, 'Judy', 'Georger');
insert into employee (id, first_name, last_name) values (213, 'Odelinda', 'Cuttin');
insert into employee (id, first_name, last_name) values (214, 'Sergei', 'Perigeaux');
insert into employee (id, first_name, last_name) values (215, 'Filberte', 'Lamberts');
insert into employee (id, first_name, last_name) values (216, 'Ilse', 'Bottinelli');
insert into employee (id, first_name, last_name) values (217, 'Rhonda', 'Roache');
insert into employee (id, first_name, last_name) values (218, 'Carola', 'Redolfi');
insert into employee (id, first_name, last_name) values (219, 'Timofei', 'Arrault');
insert into employee (id, first_name, last_name) values (220, 'Aubry', 'Treverton');
insert into employee (id, first_name, last_name) values (221, 'Lydie', 'Robuchon');
insert into employee (id, first_name, last_name) values (222, 'Cullan', 'Snalom');
insert into employee (id, first_name, last_name) values (223, 'Rodge', 'Bollen');
insert into employee (id, first_name, last_name) values (224, 'Shannen', 'Demoge');
insert into employee (id, first_name, last_name) values (225, 'Caleb', 'Savary');
insert into employee (id, first_name, last_name) values (226, 'Meier', 'Toms');
insert into employee (id, first_name, last_name) values (227, 'Ellerey', 'Franzen');
insert into employee (id, first_name, last_name) values (228, 'Maryl', 'Knibb');
insert into employee (id, first_name, last_name) values (229, 'Mandi', 'Waistall');
insert into employee (id, first_name, last_name) values (230, 'Donetta', 'Davenhall');
insert into employee (id, first_name, last_name) values (231, 'Tobiah', 'Stapford');
insert into employee (id, first_name, last_name) values (232, 'Lin', 'Muzzini');
insert into employee (id, first_name, last_name) values (233, 'Suzanne', 'O''Carran');
insert into employee (id, first_name, last_name) values (234, 'Svend', 'Langabeer');
insert into employee (id, first_name, last_name) values (235, 'Steve', 'Jepperson');
insert into employee (id, first_name, last_name) values (236, 'Tabina', 'Sporle');
insert into employee (id, first_name, last_name) values (237, 'Megen', 'Rigbye');
insert into employee (id, first_name, last_name) values (238, 'Mona', 'Paylor');
insert into employee (id, first_name, last_name) values (239, 'Felice', 'Kennerknecht');
insert into employee (id, first_name, last_name) values (240, 'Angelia', 'Macconachy');
insert into employee (id, first_name, last_name) values (241, 'Constantina', 'Blackburne');
insert into employee (id, first_name, last_name) values (242, 'Eddi', 'Cauldwell');
insert into employee (id, first_name, last_name) values (243, 'Allene', 'Verbruggen');
insert into employee (id, first_name, last_name) values (244, 'Lynn', 'Bachs');
insert into employee (id, first_name, last_name) values (245, 'Ardyce', 'Swedeland');
insert into employee (id, first_name, last_name) values (246, 'Garrott', 'Briston');
insert into employee (id, first_name, last_name) values (247, 'Ogdon', 'Galloway');
insert into employee (id, first_name, last_name) values (248, 'Dorothea', 'Hurlestone');
insert into employee (id, first_name, last_name) values (249, 'Dannie', 'Elcoat');
insert into employee (id, first_name, last_name) values (250, 'Agnesse', 'Winchcomb');
insert into employee (id, first_name, last_name) values (251, 'Carr', 'Scampion');
insert into employee (id, first_name, last_name) values (252, 'Freddie', 'Orwell');
insert into employee (id, first_name, last_name) values (253, 'Karlis', 'Lanchbury');
insert into employee (id, first_name, last_name) values (254, 'Kilian', 'Spencer');
insert into employee (id, first_name, last_name) values (255, 'Ole', 'Roskell');
insert into employee (id, first_name, last_name) values (256, 'Sal', 'Mowday');
insert into employee (id, first_name, last_name) values (257, 'Heall', 'Isley');
insert into employee (id, first_name, last_name) values (258, 'Evy', 'Sibray');
insert into employee (id, first_name, last_name) values (259, 'Mersey', 'Corder');
insert into employee (id, first_name, last_name) values (260, 'Lani', 'Routham');
insert into employee (id, first_name, last_name) values (261, 'Gerard', 'McCrohon');
insert into employee (id, first_name, last_name) values (262, 'Ingaberg', 'Jarad');
insert into employee (id, first_name, last_name) values (263, 'Bibbie', 'Boanas');
insert into employee (id, first_name, last_name) values (264, 'Mireielle', 'Towlson');
insert into employee (id, first_name, last_name) values (265, 'Leela', 'Belding');
insert into employee (id, first_name, last_name) values (266, 'Judd', 'Whipp');
insert into employee (id, first_name, last_name) values (267, 'Karna', 'Bedding');
insert into employee (id, first_name, last_name) values (268, 'Der', 'Terbeck');
insert into employee (id, first_name, last_name) values (269, 'Chadd', 'Blaxland');
insert into employee (id, first_name, last_name) values (270, 'Inglis', 'Bransdon');
insert into employee (id, first_name, last_name) values (271, 'Annetta', 'Deavall');
insert into employee (id, first_name, last_name) values (272, 'Aura', 'Bartolomivis');
insert into employee (id, first_name, last_name) values (273, 'Denis', 'Grosier');
insert into employee (id, first_name, last_name) values (274, 'Sandye', 'Lis');
insert into employee (id, first_name, last_name) values (275, 'Rennie', 'Boyington');
insert into employee (id, first_name, last_name) values (276, 'Miguela', 'Copeman');
insert into employee (id, first_name, last_name) values (277, 'Thaddeus', 'Kellington');
insert into employee (id, first_name, last_name) values (278, 'Henryetta', 'Costell');
insert into employee (id, first_name, last_name) values (279, 'Kelvin', 'Saterthwait');
insert into employee (id, first_name, last_name) values (280, 'Stefania', 'Schlagh');
insert into employee (id, first_name, last_name) values (281, 'Mildred', 'Bentham');
insert into employee (id, first_name, last_name) values (282, 'Catrina', 'Bromby');
insert into employee (id, first_name, last_name) values (283, 'Celinda', 'Broe');
insert into employee (id, first_name, last_name) values (284, 'Liuka', 'Gammidge');
insert into employee (id, first_name, last_name) values (285, 'Giana', 'Ferreri');
insert into employee (id, first_name, last_name) values (286, 'Micki', 'Kubanek');
insert into employee (id, first_name, last_name) values (287, 'Zebulen', 'Giottoi');
insert into employee (id, first_name, last_name) values (288, 'Gian', 'Pickavance');
insert into employee (id, first_name, last_name) values (289, 'Sherlocke', 'Mabbott');
insert into employee (id, first_name, last_name) values (290, 'Calla', 'Niezen');
insert into employee (id, first_name, last_name) values (291, 'Salvador', 'Mabson');
insert into employee (id, first_name, last_name) values (292, 'Claudelle', 'Juhruke');
insert into employee (id, first_name, last_name) values (293, 'Kennan', 'Briton');
insert into employee (id, first_name, last_name) values (294, 'Gray', 'Peterken');
insert into employee (id, first_name, last_name) values (295, 'Peadar', 'Whiteman');
insert into employee (id, first_name, last_name) values (296, 'Fair', 'Halvosen');
insert into employee (id, first_name, last_name) values (297, 'Kin', 'Snoxell');
insert into employee (id, first_name, last_name) values (298, 'Arleen', 'Zelake');
insert into employee (id, first_name, last_name) values (299, 'Korrie', 'Meert');
insert into employee (id, first_name, last_name) values (300, 'Iormina', 'Duley');
insert into employee (id, first_name, last_name) values (301, 'Lorraine', 'Magauran');
insert into employee (id, first_name, last_name) values (302, 'Emelina', 'Pennings');
insert into employee (id, first_name, last_name) values (303, 'Horace', 'Poynter');
insert into employee (id, first_name, last_name) values (304, 'Rasla', 'Leach');
insert into employee (id, first_name, last_name) values (305, 'Di', 'Dimitriades');
insert into employee (id, first_name, last_name) values (306, 'Eric', 'Barks');
insert into employee (id, first_name, last_name) values (307, 'Manny', 'Jonson');
insert into employee (id, first_name, last_name) values (308, 'Yvor', 'Kennerknecht');
insert into employee (id, first_name, last_name) values (309, 'Valentina', 'McCarle');
insert into employee (id, first_name, last_name) values (310, 'Leandra', 'Colomb');
insert into employee (id, first_name, last_name) values (311, 'Morgana', 'Querree');
insert into employee (id, first_name, last_name) values (312, 'Gabe', 'Dimsdale');
insert into employee (id, first_name, last_name) values (313, 'Alane', 'Leadbeater');
insert into employee (id, first_name, last_name) values (314, 'Nevile', 'Domenicone');
insert into employee (id, first_name, last_name) values (315, 'Rosita', 'Costellow');
insert into employee (id, first_name, last_name) values (316, 'Jacquenetta', 'Scobie');
insert into employee (id, first_name, last_name) values (317, 'Antony', 'Walshe');
insert into employee (id, first_name, last_name) values (318, 'Nanon', 'Risborough');
insert into employee (id, first_name, last_name) values (319, 'Susan', 'Bolens');
insert into employee (id, first_name, last_name) values (320, 'Frasquito', 'Logg');
insert into employee (id, first_name, last_name) values (321, 'Elinor', 'McIlvaney');
insert into employee (id, first_name, last_name) values (322, 'Pauli', 'Taffie');
insert into employee (id, first_name, last_name) values (323, 'Casar', 'Delaney');
insert into employee (id, first_name, last_name) values (324, 'Blakeley', 'Thomsen');
insert into employee (id, first_name, last_name) values (325, 'Terri', 'Annatt');
insert into employee (id, first_name, last_name) values (326, 'Kenton', 'Paulo');
insert into employee (id, first_name, last_name) values (327, 'Merilee', 'Fetherstone');
insert into employee (id, first_name, last_name) values (328, 'Aggie', 'Jakubovicz');
insert into employee (id, first_name, last_name) values (329, 'Bobbette', 'Chauvey');
insert into employee (id, first_name, last_name) values (330, 'Nancey', 'Pasby');
insert into employee (id, first_name, last_name) values (331, 'Boot', 'Ungerecht');
insert into employee (id, first_name, last_name) values (332, 'Nissie', 'Avrahamoff');
insert into employee (id, first_name, last_name) values (333, 'Tye', 'Tulk');
insert into employee (id, first_name, last_name) values (334, 'Hasheem', 'Itzkowicz');
insert into employee (id, first_name, last_name) values (335, 'Carrie', 'Stockau');
insert into employee (id, first_name, last_name) values (336, 'Harp', 'Geram');
insert into employee (id, first_name, last_name) values (337, 'Conn', 'Gristhwaite');
insert into employee (id, first_name, last_name) values (338, 'Florie', 'Draycott');
insert into employee (id, first_name, last_name) values (339, 'Casandra', 'Sommerville');
insert into employee (id, first_name, last_name) values (340, 'Giacinta', 'Dungey');
insert into employee (id, first_name, last_name) values (341, 'Tyne', 'Geldeard');
insert into employee (id, first_name, last_name) values (342, 'Marlow', 'Surr');
insert into employee (id, first_name, last_name) values (343, 'Deva', 'McCrachen');
insert into employee (id, first_name, last_name) values (344, 'Edgard', 'Pettecrew');
insert into employee (id, first_name, last_name) values (345, 'Kayne', 'Wink');
insert into employee (id, first_name, last_name) values (346, 'Hamid', 'Brahms');
insert into employee (id, first_name, last_name) values (347, 'Dyna', 'Schwerin');
insert into employee (id, first_name, last_name) values (348, 'Gaylene', 'Clousley');
insert into employee (id, first_name, last_name) values (349, 'Lilias', 'Foister');
insert into employee (id, first_name, last_name) values (350, 'Adriaens', 'Wiffield');
insert into employee (id, first_name, last_name) values (351, 'Rodolfo', 'Grenshiels');
insert into employee (id, first_name, last_name) values (352, 'Martin', 'Boxall');
insert into employee (id, first_name, last_name) values (353, 'Irwinn', 'Cambell');
insert into employee (id, first_name, last_name) values (354, 'Jon', 'Lippett');
insert into employee (id, first_name, last_name) values (355, 'Ricard', 'Yakobovitz');
insert into employee (id, first_name, last_name) values (356, 'Dniren', 'Worham');
insert into employee (id, first_name, last_name) values (357, 'Marie-jeanne', 'Aidler');
insert into employee (id, first_name, last_name) values (358, 'Rochester', 'Atterley');
insert into employee (id, first_name, last_name) values (359, 'Horatia', 'McReidy');
insert into employee (id, first_name, last_name) values (360, 'El', 'Castaneda');
insert into employee (id, first_name, last_name) values (361, 'Althea', 'Coverdill');
insert into employee (id, first_name, last_name) values (362, 'Jen', 'Hyman');
insert into employee (id, first_name, last_name) values (363, 'Tonye', 'Joist');
insert into employee (id, first_name, last_name) values (364, 'Shadow', 'Brentnall');
insert into employee (id, first_name, last_name) values (365, 'Alard', 'Temple');
insert into employee (id, first_name, last_name) values (366, 'Wilden', 'Earngy');
insert into employee (id, first_name, last_name) values (367, 'Rosco', 'Bedle');
insert into employee (id, first_name, last_name) values (368, 'Janice', 'Antoniat');
insert into employee (id, first_name, last_name) values (369, 'Shirl', 'Sayton');
insert into employee (id, first_name, last_name) values (370, 'Rosita', 'McCart');
insert into employee (id, first_name, last_name) values (371, 'Bonni', 'Juckes');
insert into employee (id, first_name, last_name) values (372, 'Gwenny', 'Garman');
insert into employee (id, first_name, last_name) values (373, 'Sayre', 'Dimitru');
insert into employee (id, first_name, last_name) values (374, 'Clemens', 'Mosco');
insert into employee (id, first_name, last_name) values (375, 'Genny', 'Causby');
insert into employee (id, first_name, last_name) values (376, 'Tessi', 'Mogford');
insert into employee (id, first_name, last_name) values (377, 'Jamie', 'Carbert');
insert into employee (id, first_name, last_name) values (378, 'Jasun', 'Twamley');
insert into employee (id, first_name, last_name) values (379, 'Winslow', 'Lehr');
insert into employee (id, first_name, last_name) values (380, 'Ailyn', 'Bissett');
insert into employee (id, first_name, last_name) values (381, 'Austin', 'Joontjes');
insert into employee (id, first_name, last_name) values (382, 'Mayor', 'Rusted');
insert into employee (id, first_name, last_name) values (383, 'Walther', 'Gosnall');
insert into employee (id, first_name, last_name) values (384, 'Lizette', 'Westoff');
insert into employee (id, first_name, last_name) values (385, 'Carlyn', 'Aldridge');
insert into employee (id, first_name, last_name) values (386, 'Emmi', 'Povele');
insert into employee (id, first_name, last_name) values (387, 'Winston', 'Castane');
insert into employee (id, first_name, last_name) values (388, 'Crawford', 'Doyle');
insert into employee (id, first_name, last_name) values (389, 'Grier', 'Jenkerson');
insert into employee (id, first_name, last_name) values (390, 'Salvidor', 'Kleinmintz');
insert into employee (id, first_name, last_name) values (391, 'Ardelia', 'Mann');
insert into employee (id, first_name, last_name) values (392, 'Gannie', 'Whitlaw');
insert into employee (id, first_name, last_name) values (393, 'Mahmud', 'Harnett');
insert into employee (id, first_name, last_name) values (394, 'Cayla', 'Grattan');
insert into employee (id, first_name, last_name) values (395, 'Dorothea', 'Pickle');
insert into employee (id, first_name, last_name) values (396, 'Carla', 'Juschke');
insert into employee (id, first_name, last_name) values (397, 'Asher', 'Foy');
insert into employee (id, first_name, last_name) values (398, 'Lulita', 'Thurlbeck');
insert into employee (id, first_name, last_name) values (399, 'Ollie', 'Leaning');
insert into employee (id, first_name, last_name) values (400, 'Ricard', 'Helversen');
insert into employee (id, first_name, last_name) values (401, 'Roxane', 'Mayne');
insert into employee (id, first_name, last_name) values (402, 'Trisha', 'Feek');
insert into employee (id, first_name, last_name) values (403, 'Tamiko', 'Purvey');
insert into employee (id, first_name, last_name) values (404, 'Inness', 'Dudny');
insert into employee (id, first_name, last_name) values (405, 'Brittan', 'Bushnell');
insert into employee (id, first_name, last_name) values (406, 'Alf', 'Phayre');
insert into employee (id, first_name, last_name) values (407, 'Pammie', 'Egell');
insert into employee (id, first_name, last_name) values (408, 'Adolphe', 'Poolton');
insert into employee (id, first_name, last_name) values (409, 'Emyle', 'Gussin');
insert into employee (id, first_name, last_name) values (410, 'Jan', 'Gaythwaite');
insert into employee (id, first_name, last_name) values (411, 'Toddy', 'Rumgay');
insert into employee (id, first_name, last_name) values (412, 'Annnora', 'Zavattieri');
insert into employee (id, first_name, last_name) values (413, 'Piotr', 'Binstead');
insert into employee (id, first_name, last_name) values (414, 'Anastassia', 'Wedderburn');
insert into employee (id, first_name, last_name) values (415, 'Myra', 'Fairfoot');
insert into employee (id, first_name, last_name) values (416, 'Hans', 'Gittis');
insert into employee (id, first_name, last_name) values (417, 'Elyn', 'Draco');
insert into employee (id, first_name, last_name) values (418, 'Lonny', 'Brumfield');
insert into employee (id, first_name, last_name) values (419, 'Inglebert', 'Coxen');
insert into employee (id, first_name, last_name) values (420, 'Fancie', 'Schultheiss');
insert into employee (id, first_name, last_name) values (421, 'Natalina', 'Rablin');
insert into employee (id, first_name, last_name) values (422, 'Drucill', 'Aldhous');
insert into employee (id, first_name, last_name) values (423, 'Guglielma', 'Duffin');
insert into employee (id, first_name, last_name) values (424, 'Donn', 'Moden');
insert into employee (id, first_name, last_name) values (425, 'Gussy', 'Whyatt');
insert into employee (id, first_name, last_name) values (426, 'Marieann', 'Pullman');
insert into employee (id, first_name, last_name) values (427, 'Hanny', 'Dreakin');
insert into employee (id, first_name, last_name) values (428, 'Dennie', 'Goulder');
insert into employee (id, first_name, last_name) values (429, 'Cammi', 'Crucitti');
insert into employee (id, first_name, last_name) values (430, 'Carolin', 'Sommerlin');
insert into employee (id, first_name, last_name) values (431, 'Modesty', 'Hebbs');
insert into employee (id, first_name, last_name) values (432, 'Sisile', 'Southworth');
insert into employee (id, first_name, last_name) values (433, 'Lyndsey', 'Eveling');
insert into employee (id, first_name, last_name) values (434, 'Jase', 'Yeldham');
insert into employee (id, first_name, last_name) values (435, 'Winnie', 'Wardlow');
insert into employee (id, first_name, last_name) values (436, 'Elinore', 'Izzat');
insert into employee (id, first_name, last_name) values (437, 'Scottie', 'Etoile');
insert into employee (id, first_name, last_name) values (438, 'Marris', 'Corderoy');
insert into employee (id, first_name, last_name) values (439, 'Gaelan', 'Grzelczyk');
insert into employee (id, first_name, last_name) values (440, 'Dedie', 'Burrel');
insert into employee (id, first_name, last_name) values (441, 'Scotty', 'Keiley');
insert into employee (id, first_name, last_name) values (442, 'Clementine', 'Greest');
insert into employee (id, first_name, last_name) values (443, 'Felix', 'Geertje');
insert into employee (id, first_name, last_name) values (444, 'Kriste', 'Mullard');
insert into employee (id, first_name, last_name) values (445, 'Eduardo', 'Stokell');
insert into employee (id, first_name, last_name) values (446, 'Roana', 'Stansall');
insert into employee (id, first_name, last_name) values (447, 'Coletta', 'Eden');
insert into employee (id, first_name, last_name) values (448, 'Marietta', 'Biddell');
insert into employee (id, first_name, last_name) values (449, 'Alecia', 'Shilston');
insert into employee (id, first_name, last_name) values (450, 'Jamie', 'Oxherd');
insert into employee (id, first_name, last_name) values (451, 'Nahum', 'Anfusso');
insert into employee (id, first_name, last_name) values (452, 'Salomi', 'Anchor');
insert into employee (id, first_name, last_name) values (453, 'Helenelizabeth', 'Guild');
insert into employee (id, first_name, last_name) values (454, 'Agnesse', 'Bloyes');
insert into employee (id, first_name, last_name) values (455, 'Rayner', 'Hodjetts');
insert into employee (id, first_name, last_name) values (456, 'Zora', 'Gresty');
insert into employee (id, first_name, last_name) values (457, 'Corny', 'Pieters');
insert into employee (id, first_name, last_name) values (458, 'Flemming', 'Griswaite');
insert into employee (id, first_name, last_name) values (459, 'Vick', 'Bernadon');
insert into employee (id, first_name, last_name) values (460, 'Lissy', 'Antoniades');
insert into employee (id, first_name, last_name) values (461, 'Eartha', 'Gosz');
insert into employee (id, first_name, last_name) values (462, 'Fayina', 'Escoffrey');
insert into employee (id, first_name, last_name) values (463, 'Ryann', 'Pottes');
insert into employee (id, first_name, last_name) values (464, 'Lila', 'Trounson');
insert into employee (id, first_name, last_name) values (465, 'Zoe', 'Fagg');
insert into employee (id, first_name, last_name) values (466, 'Claus', 'Whithalgh');
insert into employee (id, first_name, last_name) values (467, 'Lowe', 'Decaze');
insert into employee (id, first_name, last_name) values (468, 'Caleb', 'Baignard');
insert into employee (id, first_name, last_name) values (469, 'Sophie', 'Greatbanks');
insert into employee (id, first_name, last_name) values (470, 'Carla', 'Domoni');
insert into employee (id, first_name, last_name) values (471, 'Laurens', 'Byway');
insert into employee (id, first_name, last_name) values (472, 'Sandi', 'Yarwood');
insert into employee (id, first_name, last_name) values (473, 'Karylin', 'Camous');
insert into employee (id, first_name, last_name) values (474, 'Barrie', 'Ramshay');
insert into employee (id, first_name, last_name) values (475, 'Artus', 'Colborn');
insert into employee (id, first_name, last_name) values (476, 'Tressa', 'Coles');
insert into employee (id, first_name, last_name) values (477, 'Collette', 'Bernini');
insert into employee (id, first_name, last_name) values (478, 'Allina', 'Bernier');
insert into employee (id, first_name, last_name) values (479, 'Haleigh', 'Hallad');
insert into employee (id, first_name, last_name) values (480, 'Chuck', 'McBean');
insert into employee (id, first_name, last_name) values (481, 'Russ', 'Blacket');
insert into employee (id, first_name, last_name) values (482, 'Esteban', 'Whoolehan');
insert into employee (id, first_name, last_name) values (483, 'Lanie', 'Cassella');
insert into employee (id, first_name, last_name) values (484, 'Conchita', 'Selcraig');
insert into employee (id, first_name, last_name) values (485, 'Ludwig', 'Duhig');
insert into employee (id, first_name, last_name) values (486, 'Josephina', 'Skill');
insert into employee (id, first_name, last_name) values (487, 'Tootsie', 'Nestor');
insert into employee (id, first_name, last_name) values (488, 'Free', 'McShee');
insert into employee (id, first_name, last_name) values (489, 'Temple', 'Brideau');
insert into employee (id, first_name, last_name) values (490, 'Brandyn', 'Dungate');
insert into employee (id, first_name, last_name) values (491, 'Melisenda', 'Codi');
insert into employee (id, first_name, last_name) values (492, 'Gilberte', 'Haughian');
insert into employee (id, first_name, last_name) values (493, 'Carole', 'Aspell');
insert into employee (id, first_name, last_name) values (494, 'Nanete', 'Lewnden');
insert into employee (id, first_name, last_name) values (495, 'Angel', 'Hogsden');
insert into employee (id, first_name, last_name) values (496, 'Donal', 'Sperwell');
insert into employee (id, first_name, last_name) values (497, 'Zahara', 'Lange');
insert into employee (id, first_name, last_name) values (498, 'Felic', 'Menlove');
insert into employee (id, first_name, last_name) values (499, 'Cy', 'Cristoforetti');
insert into employee (id, first_name, last_name) values (500, 'Caitrin', 'Lomis');
